<a href="https://colab.research.google.com/github/DD-bit001/deep_learning_practice/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)


2.11.0+cu128


In [3]:
if torch.cuda.is_available():
    print("GPU is available")
    print(torch.cuda.get_device_name(0))
    print(torch.cuda.device_count())
    print(torch.cuda.current_device())
else:
    print("cuda is not available")

GPU is available
Tesla T4
1
0


In [5]:
torch.empty(2,3) #this fun just allocate the memory
a=torch.empty(2,3) #this fun just allocate the memory

In [6]:
type(a)

torch.Tensor

In [7]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
torch.rand(2,3)

tensor([[0.3591, 0.3743, 0.9744],
        [0.3123, 0.4097, 0.4816]])

In [10]:
torch.rand(2,3)

tensor([[0.9539, 0.5582, 0.1267],
        [0.6442, 0.1048, 0.4867]])

In [11]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
torch.manual_seed(100) #same seed same output
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [15]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


Tensors Shape


In [16]:
x=torch.tensor([[1,2,3],[4,5,6]])


In [17]:
x.shape

torch.Size([2, 3])

In [18]:
torch.empty_like(x) #copying shape of x

tensor([[726385344, 727908704,         0],
        [        0,         1,         0]])

In [ ]:
#torch.zeros_like, torch_ones_like

In [19]:
x.dtype

torch.int64

In [21]:
#assign dtype
torch.tensor([[1,2,3,4]],dtype=torch.float64)

tensor([[1., 2., 3., 4.]], dtype=torch.float64)

In [22]:
#changing the dtype
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [23]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [25]:
# add, sub, mul, scaler operation
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [26]:
x*100

tensor([[100, 200, 300],
        [400, 500, 600]])

In [27]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [28]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [29]:
y=torch.tensor([[4,5,6],[7,8,9]])


element wiae hota h

In [30]:
x+y

tensor([[ 5,  7,  9],
        [11, 13, 15]])

In [31]:
x*y

tensor([[ 4, 10, 18],
        [28, 40, 54]])

In [32]:
x/y

tensor([[0.2500, 0.4000, 0.5000],
        [0.5714, 0.6250, 0.6667]])

In [33]:
torch.abs(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [34]:
torch.round(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [35]:
torch.ceil(x)
torch.floor(x)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [36]:
torch.clamp(x,min=2,max=3) # sbkuch range me aa jayega

tensor([[2, 2, 3],
        [3, 3, 3]])

In [40]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
torch.sum(x)

tensor(21)

In [38]:
#sum along colums
torch.sum(x,dim=0)

tensor([5, 7, 9])

In [39]:
#sum along rows
torch.sum(x,dim=1)

tensor([ 6, 15])

In [43]:
y=torch.tensor([[1,2,3],[4,5,6],[7,8,9]],dtype=torch.float32)

In [44]:
torch.mean(y)

tensor(5.)

In [45]:
torch.mean(y,dim=0)

tensor([4., 5., 6.])

In [46]:
# meadian , max , min, product , std, var ,

In [48]:
torch.argmax(y) # max ka positon bataya ga

tensor(8)

In [49]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[8, 8, 4],
        [4, 1, 0]])
tensor([[4, 3],
        [8, 7],
        [4, 6]])


In [50]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[112, 104],
        [ 24,  19]])

In [51]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [52]:
# transpose
torch.transpose(f, 0, 1)

tensor([[8, 4],
        [8, 1],
        [4, 0]])

In [57]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)

In [58]:
# determinant
torch.det(h)

tensor(-504.)

In [59]:
# inverse
torch.inverse(h)

tensor([[ 0.0000,  0.0000,  0.1429],
        [-0.0000,  0.1250, -0.1607],
        [ 0.1111, -0.0139,  0.0179]])

In [60]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 5, 7],
        [3, 9, 4]])
tensor([[0, 5, 7],
        [5, 9, 9]])


In [61]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to

# less than equal to

tensor([[ True, False, False],
        [ True, False,  True]])

In [62]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[7., 5., 9.],
        [8., 9., 7.]])

In [63]:
# log
torch.log(k)

tensor([[1.9459, 1.6094, 2.1972],
        [2.0794, 2.1972, 1.9459]])

In [64]:
# exp
torch.exp(k)

tensor([[1096.6332,  148.4132, 8103.0840],
        [2980.9580, 8103.0840, 1096.6332]])

In [65]:
# sqrt
torch.sqrt(k)

tensor([[2.6458, 2.2361, 3.0000],
        [2.8284, 3.0000, 2.6458]])

In [66]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9991, 0.9933, 0.9999],
        [0.9997, 0.9999, 0.9991]])

In [67]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.2689, 0.0180, 0.8808],
        [0.7311, 0.9820, 0.1192]])

In [68]:
# relu
torch.relu(k)

tensor([[7., 5., 9.],
        [8., 9., 7.]])

Inplace operation

In [69]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.7278, 0.4563, 0.3389],
        [0.6211, 0.5530, 0.6896]])
tensor([[0.3687, 0.9053, 0.8356],
        [0.3039, 0.6726, 0.5740]])


In [70]:
m+n

tensor([[1.0966, 1.3615, 1.1744],
        [0.9251, 1.2256, 1.2636]])

In [71]:
m.add_(n)

tensor([[1.0966, 1.3615, 1.1744],
        [0.9251, 1.2256, 1.2636]])

In [72]:
m

tensor([[1.0966, 1.3615, 1.1744],
        [0.9251, 1.2256, 1.2636]])

In [73]:
torch.relu(m)

tensor([[1.0966, 1.3615, 1.1744],
        [0.9251, 1.2256, 1.2636]])

In [74]:
m.relu_()

tensor([[1.0966, 1.3615, 1.1744],
        [0.9251, 1.2256, 1.2636]])

Copying the tensors

In [75]:
a = torch.rand(2,3)
a

tensor([[0.9233, 0.9178, 0.7590],
        [0.7775, 0.6179, 0.3379]])

In [76]:
b = a

In [77]:
a[0][0] = 0

In [78]:
a

tensor([[0.0000, 0.9178, 0.7590],
        [0.7775, 0.6179, 0.3379]])

In [79]:
b

tensor([[0.0000, 0.9178, 0.7590],
        [0.7775, 0.6179, 0.3379]])

In [80]:
id(a)

140063919185808

In [81]:
id(b)

140063919185808

In [88]:
a[0][0] = 10

In [85]:
b=a.clone()

In [89]:
a

tensor([[10.0000,  0.9178,  0.7590],
        [ 0.7775,  0.6179,  0.3379]])

In [90]:
b

tensor([[10.0000,  0.9178,  0.7590],
        [ 0.7775,  0.6179,  0.3379]])

In [91]:
id(a)


140063919185808

In [92]:
id(b)

140063919255664

Tensors operations on GPU

In [93]:
torch.cuda.is_available()

True

In [94]:
device=torch.device('cuda')

In [95]:
torch.rand((2,3),device=device)

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [96]:
a=torch.rand((2,3))

In [97]:
b=a.to(device)

In [98]:
b+5

tensor([[5.2170, 5.9454, 5.7116],
        [5.1157, 5.6574, 5.3451]], device='cuda:0')

In [99]:
import time
size=10000
maxtrix1=torch.rand(size,size)
maxtrix2=torch.rand(size,size)

#Measure time on cpu
start_time=time.time()
result_cpu=torch.matmul(maxtrix1,maxtrix2)
end_time=time.time()
print("Time taken on cpu",end_time-start_time)

mat1_gpu=maxtrix1.to('cuda')
mat2_gpu=maxtrix2.to('cuda')
#Measure time on gpu
start_time=time.time()
result_gpu=torch.matmul(mat1_gpu,mat2_gpu)
end_time=time.time()
print("Time taken on gpu",end_time-start_time)
#

Time taken on cpu 16.672008275985718
Time taken on gpu 0.1134023666381836


In [100]:
a=torch.ones(4,4)

In [101]:
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [103]:
#flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [105]:
b=torch.rand(2,3,4)
b


tensor([[[0.9514, 0.0141, 0.8903, 0.1649],
         [0.3162, 0.1331, 0.6763, 0.4254],
         [0.2375, 0.5430, 0.1174, 0.6532]],

        [[0.5115, 0.3094, 0.7907, 0.7351],
         [0.2693, 0.8009, 0.5839, 0.0061],
         [0.4671, 0.8243, 0.2861, 0.7459]]])

In [107]:
b.permute(2,0 ,1)


tensor([[[0.9514, 0.3162, 0.2375],
         [0.5115, 0.2693, 0.4671]],

        [[0.0141, 0.1331, 0.5430],
         [0.3094, 0.8009, 0.8243]],

        [[0.8903, 0.6763, 0.1174],
         [0.7907, 0.5839, 0.2861]],

        [[0.1649, 0.4254, 0.6532],
         [0.7351, 0.0061, 0.7459]]])

In [108]:
c=torch.rand(226,226,3)


In [109]:
c.unsqueeze(0).shape #batch ke liye

torch.Size([1, 226, 226, 3])

In [111]:
c.squeeze(0).shape

torch.Size([226, 226, 3])

In [112]:
import numpy as np

b=c.numpy()

In [114]:
type(b)

numpy.ndarray

In [115]:
torch.from_numpy(b)

tensor([[[0.8487, 0.4059, 0.2883],
         [0.2220, 0.6423, 0.7098],
         [0.5644, 0.4549, 0.0729],
         ...,
         [0.4378, 0.8047, 0.3651],
         [0.0630, 0.9183, 0.0861],
         [0.9756, 0.1175, 0.9696]],

        [[0.4014, 0.8289, 0.4343],
         [0.8286, 0.0097, 0.4689],
         [0.7481, 0.6284, 0.7681],
         ...,
         [0.8594, 0.4732, 0.2077],
         [0.9188, 0.7575, 0.8535],
         [0.5775, 0.4705, 0.8696]],

        [[0.3757, 0.1533, 0.9881],
         [0.4648, 0.2386, 0.8656],
         [0.7935, 0.3718, 0.3230],
         ...,
         [0.7167, 0.4770, 0.0998],
         [0.2141, 0.5962, 0.9068],
         [0.1834, 0.4347, 0.9546]],

        ...,

        [[0.2906, 0.5791, 0.2177],
         [0.4913, 0.5510, 0.8402],
         [0.1218, 0.2787, 0.6245],
         ...,
         [0.1008, 0.8294, 0.1528],
         [0.3117, 0.8750, 0.2646],
         [0.5109, 0.0817, 0.7453]],

        [[0.4627, 0.4627, 0.2822],
         [0.9050, 0.8155, 0.4537],
         [0.

In [116]:
!git init
!git add .
!git commit -m "first commit"
!git push origin main

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/
Author identity unknown

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'root@191ae4f9a3cc.(none)')
error: src refspec main does not match any
error: failed to push some refs to 'origin'


In [117]:
!git config --global user.name "Md Dilnawaz Ahmad"
!git config --global user.email "ahmad.dilnawaz.md@gmail.com"

In [120]:
!git init
!git add .
!git commit -m "first commit"
!git push origin main

Reinitialized existing Git repository in /content/.git/
[master (root-commit) f4df658] first commit
 21 files changed, 51059 insertions(+)
 create mode 100644 .config/.last_opt_in_prompt.yaml
 create mode 100644 .config/.last_survey_prompt.yaml
 create mode 100644 .config/.last_update_check.json
 create mode 100644 .config/active_config
 create mode 100644 .config/config_sentinel
 create mode 100644 .config/configurations/config_default
 create mode 100644 .config/default_configs.db
 create mode 100644 .config/gce
 create mode 100644 .config/hidden_gcloud_config_universe_descriptor_data_cache_configs.db
 create mode 100644 .config/logs/2026.05.26/13.30.34.238876.log
 create mode 100644 .config/logs/2026.05.26/13.30.51.777284.log
 create mode 100644 .config/logs/2026.05.26/13.31.07.426506.log
 create mode 100644 .config/logs/2026.05.26/13.31.08.786403.log
 create mode 100644 .config/logs/2026.05.26/13.31.21.680598.log
 create mode 100644 .config/logs/2026.05.26/13.31.22.451851.log
 crea